# -*- coding: utf-8 -*-
"""Score

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-xGW3Zko9Z6vm06bOvnFmBmyroXd7yA
"""

grades = list(map(int, input().split()))
count = 0
total = 0
for grade in grades:
  total += grade
  if(grade<60):
    count+=1
print(count)
print(total / len(grades))